#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartHome.Droid.Resource", IsApplication=true)]

namespace SmartHome.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int change = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int find = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int glasses = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int header_br = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int home = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int message = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int more = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int more_desk = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int more_home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int more_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int more_info = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int more_like = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int more_setting = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notification = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int online = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int products = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int rectangle = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sbg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int setting = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int un_sbg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int user_bg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int user_icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int warning = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
